### ISSUE TITLE
log4net dependency

### ISSUE THREAD

**Issue by doerig** [csnemes/tracer#14]
I tried to use tracer with the newest log4net assembly installed (1.2.15), but the application failed to load. I had to revert log4net to version 1.2.13. It looks like there is an reference with this specific version defined in tracer.log4net.

**Comment by csnemes** [comment]
Log4net uses strong-named assembly so the referenced version must match. You can put an assembly redirect into your application configuration file like the following:
```
<configuration>
.....
   <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="log4net" publicKeyToken="669e0ddf0bb1aa2a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2.15.0" newVersion="1.2.15.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
...
</configuration>
```

In the forthcoming days I'll release a new version of the library recompiled with the new version.

**Comment by csnemes** [comment]
Created a new package for Tracer.log4net.fody (1.2.1) which supports log4net package 2.0.5 with the new dll.

**Comment by doerig** [comment]
thank you :+1:
