### ISSUE TITLE
Tracer Ignoring My NoTrace Attribute in Custom Implementation

### ISSUE THREAD

**Issue by jkruer01** [csnemes/tracer#18]
I created my own Logging Adapter and implemented a NoTrace attribute as discussed in [https://github.com/csnemes/tracer/wiki/Create-your-own-logging-adapter](url) 

I have added [NoTrace] to many classes but those methods are still getting logged.  What do I have to do in order to make Tracer recognize and abide by my NoTrace attribute?

**Comment by csnemes** [comment]
Could you please check if the namespace for the attribute is correct? The full name of the attribute should be TracerAttributes.NoTrace. Do you use the DefaultFilter or using a custom one? (I don't think that you use a custom one just to make sure.) 
Also please send me your attribute definition and a usage example so I can try to reproduce the problem.
Thanks.

**Comment by jkruer01** [comment]
Changing the Name Space Worked.  I didn't realize that was required.  Thanks!
