### ISSUE TITLE
System.TypeInitializationException when logging .cctor()

### ISSUE THREAD

**Issue by radudami** [csnemes/tracer#20]
If you have a static initialized value defined in the class and you set TraceOn to private, a TypeInitializationException gets thrown.

Steps to reproduce:
1. Add a static initialized property to the MyApplication class:
`public class MyApplication
    {
        private static string x = "abc";
}`
2. Set TraceOn to private:
`<TraceOn class="private" method="private" />`
3. Run the application
You'll get:

> Unhandled Exception: System.TypeInitializationException: The type initializer for 'TestApplication.MyApplication' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at TestApplication.MyApplication..cctor() in \tracer\TestApplication\MyApplication.cs:line 17
   --- End of inner exception stack trace ---
   at TestApplication.MyApplication..ctor()
   at TestApplication.Program.Main(String[] args) in \tracer\TestApplication\Program.cs:line 21

**Comment by csnemes** [comment]
Hi,
It turned out that the problem wasn't the static value but an outdated reference to an older log4net library. I've updated the log4net package to version 2.0.5 in the TestApplication and now it works. (When I updated the tracer.log4net adapter to the newer log4net I completely forgot to update this test project)

**Comment by csnemes** [comment]
Also the constructor rewriting had to be changed so it would not trace static constructors. Probably your error is referred to this problem. I'll put the fix in the next release.

**Comment by radudami** [comment]
Thank you for addressing this.

**Comment by csnemes** [comment]
Fixed in 1.3
