### ISSUE TITLE
Serilog adapter doesn't work

### ISSUE THREAD

**Issue by Leon99** [csnemes/tracer#32]
Even the provided sample application (TestApplication.Serilog) doesn't produce any logs, while the Log4net sample works just fine for me.

**Comment by csnemes** [comment]
It was my mistake, I forgot to add the fody xml configuration to the sample application (I run weaving from a unit test). Now the sample should work using the latest master source.

**Comment by Leon99** [comment]
Yep the sample works now, though my app still doesn't (but that's a different story...) Cheers
