### ISSUE TITLE
Warning when you use Tracer.Serilog with .net framework v4.5

### ISSUE THREAD

**Issue by ammaroff** [csnemes/tracer#34]
This warning is appear when you use it with  any version below v.4.6.1
`warning MSB3274: The primary reference "Tracer.Serilog, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.6.1" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5"`

I think it will be good if you make the target framework to target the minimum version that support `Serilog` and `Fody`
Ref: https://github.com/csnemes/tracer/blob/master/Tracer.Serilog/Tracer.Serilog.csproj#L12

**Comment by csnemes** [comment]
I've set the Tracer.Serilog .NETfwork version to 4.5
