### ISSUE TITLE
Can you add support for Xamarin.Forms targets?

### ISSUE THREAD

**Issue by Emasoft** [csnemes/tracer#37]
This is a great library, I'd like to use it in my Xamarin.Forms projects. Unfortunately it seems that there is some incompatibility in the NuGet package profile. Those are the errors I get when I try to add it to my Xamarin.Forms project: 

> Could not install package 'log4net 2.0.5'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

> Could not install package 'log4net 2.0.5'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

>Could not install package 'log4net 2.0.5'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v7.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

The same is true with Serilog adapter:

>Could not install package 'Tracer.Serilog.Fody 1.0.1'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

etc.

Note that installing Serilog nuget package and the Fody package separatedly works perfectly fine.

Can you help me with that? Thank you.

**Comment by csnemes** [comment]
Hi,
Unfortunatelly, neither log4net, nor serilog supports the Xamarin platform as far as I understood. I take a quick look on other loggers and it seems that NLog is supporting the Xamarin platform. So a solution would be to use an NLog adapter. The good thing is that NLog adaper is almost ready, I'll try to finish and release it in the forthcoming week.

**Comment by csnemes** [comment]
I've just released the NLog adapter (Tracer.4NLog.Fody). As NLog supports Xamarin it should probably work, give it a try.

**Comment by WebDucer** [comment]
Hi.

With NLog it works, if I add the dependency manually (currently testet on Android). But you can not install the nuget package, because this is only targeting net40 (no pcl).

I'll try to create a pull request, so that nuget package works with  Xamarin (and PCL) projects.

**Comment by csnemes** [comment]
Hi, Could you please check the 2.0 version which is now on netstandard 2.0. As far as I understand netstd 2.0 should work with Xamarin.
