### ISSUE TITLE
Serilog - is there a way to destructure the return value?

### ISSUE THREAD

**Issue by Hainesy** [csnemes/tracer#41]
The details provided by the trace output are great, but when the return value is anything other than a scalar, it's not ideal. In Serilog, there is a way to destructure return values using the '@' symbol. Any way to do this with Tracer.Serilog?

**Comment by csnemes** [comment]
At first glance it seems feasible. My first guess is that the LoggerAdapter for Serilog should be changed to use StructureValue instead of ScalarValue when building TraceLeave event. I'll try to check if this approach works and create a new release if it does.

**Comment by csnemes** [comment]
Technically I managed to change the trace enter and trace leave to output incoming parameters and return values using serilog destructure. My problem is that if I leave it this way all classes will be logged in destructured form. So I think somehow the user should decide on which classes should be destructured and which ones should not. I'm pretty sure that this behaviour should be opt-in, same way as in Serilog. What would be a good way to let the system know which classes to destructure? Using some custom attribute on classes? (What should we do with classes without source code (libraries, framework, etc)?) Should we allow some configuration file where these classes can be listed? Any thoughts on this from user's perspective?

**Comment by Hainesy** [comment]
Maybe make it opt-in at either return type or method-level, i.e. you can either add an attribute to the method to tell it to destructure the return type (covers classes without source code), or you can add an attribute to custom classes to tell it to always destructure this type.

**Comment by csnemes** [comment]
Updated the package to 1.1 which now supports using DestructureAttribute on types you wish to destructure on trace enter and leave. Also added an assembly level DestructureTypeAttribute which can be used to add types outside your codebase. The method-level thing is a lot more involved as the rewriter itself should be changed. I'm planing on the vNext of the rewriter and I'll definitely add some mechanism to it which will make this scenario possible.
