### ISSUE TITLE
Can you add a DestructureAttribute support for Tracer.4NLog target

### ISSUE THREAD

**Issue by avighawali** [csnemes/tracer#44]
This is an awesome library and information provided by the trace output are great.

I have already integrated library in my projects and it is working great with NLog adapter. But unfortunately, it is not logging the custom class input and output in log file.

I saw in another post there is something DestructureAttribute support added in Tracer.SeriLog library.

Can we have same DestructureAttribute feature in Tracer.4NLog target, so that input and output of custom classes can be trace in log file.

Thank-you in advance!

**Comment by csnemes** [comment]
Hi,

The destructuring is part of the Serilog library the attribute is only there to enable the use of it. (Serilog requires the destructuring directive to be the part of the message template used for logging, but you cannot specify the template for trace enter and trace leave messages direclty, hence the attribute). If NLog has some similar capability I think I can create some similar mechanism to let the logger know when to apply destructuring. I use NLog rarerly so I need to take a look if destructuring exists there is some form.
