### ISSUE TITLE
How to target the Tracer output from NLog.config?

### ISSUE THREAD

**Issue by gautelo** [csnemes/tracer#50]
Hi,

I'm having some trouble turning my tracer output on/off through my NLog.config.

I'm using Tracer.4NLog.Fody 1.0.1 and Tracer.Fody 1.6.0 with NLog.Extensions.Logging 1.0.0-rtm-beta4 and NLog 4.4.11.

What I want to do is turn on all logging, and then turn off certain namespaces using `final="true"`
```xml
  <rules>
    
    <!--Ignore certain namespaces-->
    <logger name="LogWeb5.*" minlevel="Trace" final="true" writeTo="void" /><!-- Works -->
    <logger name="Tracer.*" minlevel="Trace" final="true" writeTo="void" /><!-- Doesn't work -->
    
    <!-- Include others -->
    <logger name="*" minlevel="Trace" writeTo="log" />
  
  </rules>
```
Alternatively I could turn on specific namespaces
```xml
  <rules>
    <logger name="Tracer.*" minlevel="Trace" writeTo="log" />
    <logger name="LogWeb5.*" minlevel="Trace" writeTo="log" />
  </rules>
```

Since I'm getting output from Tracer in the first case, I must conclude that I've set up Tracer correctly. It seems like I'm simply trying to target Tracer in the wrong way. It's like it's using a different namespace internally to decide if it should be written or not. That namespace would then be matched when I use the `name="*"` catch-all type of configuration.

While the insight given by Tracer is great, I don't want its output to be on at all times. I want to be able to toggle the output so that I can turn it on when I need it. Any help on how to achieve that would be greatly appreciated!

Thanks for a very cool tool! Cheers!

**Comment by csnemes** [comment]
Hi,
Thanks.
From the logger’s point of view (be it nlog, log4net or something else) tracer uses the namespace and the class of the original code. So it works as if you had manually added the entry and leave logging to your methods using a logger created for each class. At least it should work this way. I cannot access the source code at the moment, so I'm not able to double check it. I hope this helps. Please let me know if you have any further question.

Best regards
Csaba

**Comment by gautelo** [comment]
What you're saying would make sense, and would, in my opinion, be a better implementation choice than having a separate namespace for the Tracer logger. So, if that's the intended functionality, that's great.

If it is, though, I find it surprising that my logs (with the * log) looks like this:

```
Tracer.NLog.Adapters.LoggerAdapter.LogTrace  Entered into Get().
LogWeb5.Controllers.SomeController.Get SomeCtrl Some asked to get it!
Tracer.NLog.Adapters.LoggerAdapter.LogTrace SomeCtrl Entered into DoSomething().
LogWeb5.SomethingSvc.DoSomething SomeCtrl Begin DoSomething
Tracer.NLog.Adapters.LoggerAdapter.LogTrace SomeCtrl->Do Entered into SideEffects().
LogWeb5.SomethingSvc.SideEffects SomeCtrl->Do No side effects!
Tracer.NLog.Adapters.LoggerAdapter.LogTrace SomeCtrl->Do Returned from SideEffects() (). Time taken: 1,63 ms.
Tracer.NLog.Adapters.LoggerAdapter.LogTrace SomeCtrl->Do Entered into DoOther().
Tracer.NLog.Adapters.LoggerAdapter.LogTrace SomeCtrl->Do Returned from DoOther() (). Time taken: 0,00 ms.
LogWeb5.SomethingSvc.DoSomething SomeCtrl End DoSomething
Tracer.NLog.Adapters.LoggerAdapter.LogTrace SomeCtrl Returned from DoSomething() (). Time taken: 12,73 ms.
Tracer.NLog.Adapters.LoggerAdapter.LogTrace  Returned from Get() ($return=System.String[]). Time taken: 17,74 ms.
```
Where I would have expected something like the following, which I find much easier to read:
```
LogWeb5.Controllers.SomeController  Entered into Get().
LogWeb5.Controllers.SomeController.Get SomeCtrl Some asked to get it!
LogWeb5.Controllers.SomeController SomeCtrl Entered into DoSomething().
LogWeb5.SomethingSvc.DoSomething SomeCtrl Begin DoSomething
LogWeb5.SomethingSvc SomeCtrl->Do Entered into SideEffects().
LogWeb5.SomethingSvc.SideEffects SomeCtrl->Do No side effects!
LogWeb5.SomethingSvc SomeCtrl SomeCtrl->Do Returned from SideEffects() (). Time taken: 1,63 ms.
LogWeb5.OtherSvc SomeCtrl->Do Entered into DoOther().
LogWeb5.OtherSvc SomeCtrl->Do Returned from DoOther() (). Time taken: 0,00 ms.
LogWeb5.SomethingSvc SomeCtrl End DoSomething
LogWeb5.SomethingSvc SomeCtrl Returned from DoSomething() (). Time taken: 12,73 ms.
LogWeb5.Controllers.SomeController  Returned from Get() ($return=System.String[]). Time taken: 17,74 ms.
```
If it is indeed the case that the resulting logged namespaces do not match the internally used namespace, I can't make sense of that either, however. Why? Cause turning on everything except "LogWeb5.*" does not turn off the Tracer output. Likewise, turning on only "LogWeb5" does not also turn off the Tracer output.

**Comment by csnemes** [comment]
The internal namespaces of the Tracer adapter should not appear in the log at all. In the adapter LogEventInfo instances are crafted 'manually' to mimic the right behaviour. It seems that in your case it isn't working. I'll check this issue trying to reproduce the error, Unfortunately I can only do this at the end of next week as I'm on holidays,

**Comment by gautelo** [comment]
Great stuff. Enjoy your holliday!

I uploaded my [test repository](https://github.com/gautelo/csnemes-tracer-issues-50) in order to let you more easily debug the issue, when you get back.

**Comment by csnemes** [comment]
Hi,
This is a bug in the adapter, I forgot to set the wrapperType when calling the logger. I will fix it.
One drawback I realised when looking through NLog is that unfortunately it seems very difficult to make use of the speed enhancement of Tracer. NLog internally always runs the StackTrace, I'm not able to inject the method and class information to it although it is there statically at rewrite time (One of the reasons I created Tracer is to get rid of the time consuming StackTrace for each log entry). Anyway it should work properly, after the fix of course.

**Comment by gautelo** [comment]
That's great news!

I'm not sure exactly what you mean by it running the StackTrace. That sounds like a very large overhead. Why would it need to investigate the stack? Imho stack trace investigation should only happen when exceptions are thrown, not when logging normal things.

Does this mean there is significant performance implications with choosing NLog over one of the other logging frameworks?

I mean, clearly Tracer adds a lot of log writes, so I guess log perf is more important when using Tracer than it would be with more usual sparse logging..

**Comment by csnemes** [comment]
The issue is fixed in the 1.0.3 version of the NLog adapter, please give it a try. About the stack trace thing: All logging frameworks use the stack trace to figure out the callsite, that is, from which method the logger was called. One of the benefits of using tracer is that during the rewrite phase we know all the callsites so we can pass this information to the logger so there's no need to figure out the callsite from the stack trace. There are logging frameworks (like log4net) where I can inject this information into the logging mechanism and some (like NLog) where I cannot (or at least I haven't find a way to do it yet).

**Comment by gautelo** [comment]
Great news. I'll check it out and post my findings. Thanks!

So, I felt pretty sure you shouldn't have to look up the logger name from the stack with NLog, so I looked up the details. Seems to me the stack is only used if you instantiate the logger using  `LogManager.GetCurrentClassLogger()`, but not if you do using `LogManager.GetLogger("My.Call.Site.MyClass")` or `LogManager.GetLogger(typeof(MyClass).FullName)`.

Also, the stack is only looked up to find out which class is instantiating it, not to figure out which method is writing to the log; a very big difference.

If however there is further lookup to the stack in other places, what I'm saying here is rubish, but I don't see why there would be any need to.

**Comment by csnemes** [comment]
Now I see we're talking about two different things and it seems that we're both right :-). What I fixed was the callsite property which you used to display the calling method in your logs. There NLog uses stack trace for every call. The rule filtering on the other hand is based on the Logger name and not on the callsite. There I've just found a bug of not using FullName but Name of the type, so that might caused the error. The callsite thing on the other hand can be substituted with ${event-properties:item=TypeInfo} and ${event-properties:item=MethodInfo}. These two are injected by Tracer to provide the same info as the callsite without the overhead of running a stack trace. Please ignore the 1.0.3 release as it will still misbehave (the callsite will be OK, but that wasn't the point).

**Comment by gautelo** [comment]
Ahh.. I see.. yes.. all loggers I suppose will use the stack to figure out the call site method name, indeed. Hopefully only when a logger is active (but I digress).

Yep.. was testing 1.0.3, and found that the names were now right, but that I still couldn't control filtering the way I want.

Eagerly awaiting 1.0.4 :)

**Comment by csnemes** [comment]
Just published to nuget, it should be visible soon.
As far as I understood the NLog code it only runs the stack trace if one of the logging outputs uses the callsite property. So someone instead of referencing callsite uses the TypeInfo and MethodInfo properties can avoid the performance penalty and still have the information on the call's location.

**Comment by gautelo** [comment]
Yep. That did it. Thanks a bunch!

As for the MethodInfo and such, I think I should probably measure perf impact before I try to optimize. "Premature optimization is the root of all evil", after all. As far as I am concerned the Tracer output should be turned off by default, and only turned on during diagnostic sessions, which should work great now.
