### ISSUE TITLE
Log4Net version mismatch

### ISSUE THREAD

**Issue by Janek91** [csnemes/tracer#54]
I got such error
FileLoadException: Could not load file or assembly 'log4net, Version=1.2.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

due to this entry 

    <Reference Include="log4net, Version=1.2.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a, processorArchitecture=MSIL">
      <HintPath>..\packages\log4net.2.0.5\lib\net40-full\log4net.dll</HintPath>
      <Private>True</Private>
    </Reference>
	
in https://github.com/csnemes/tracer/blob/master/Tracer.Log4net/Tracer.Log4net.csproj#L34 file

**Comment by gautelo** [comment]
@Janek91 I'd be a bit surprised if version 1.2.15 of log4net was to be found in the 2.0.5 package. I'd try changing the versions so that they match in all and any of your app.config/web.config, packages.config and *.csproj.

**Comment by Janek91** [comment]
@gautelo but it's not an entry in any of mine *.csproj files, but in yours one:
 https://github.com/csnemes/tracer/blob/master/Tracer.Log4net/Tracer.Log4net.csproj#L34
In addition it's a bug in 2.0.5 version of log4net NuGet package. So, please, either fix manually path to correct dll in Tracer.Log4net.csproj file or update log4net to version above 2.0.5. I can prepare such commit on my fork, but I don't know which option do you prefer.

**Comment by gautelo** [comment]
@Janek91 Aha. I see. I was under the impression that the snippet was in your csproj. Apparently I need reading lessons. Clear cut bug then. Might be a merging issue or something. In any event, I'm sure @csnemes will fix it for you in a jiffy.

**Comment by Janek91** [comment]
Still no fix. I was able to create package for my own purposes, but others will be having the same problem. As I said previously - it's a bug in log4net ver. 2.0.5 - just upgrade it a bit, please.

**Comment by csnemes** [comment]
Ok. I'll update it to the latest 2.0.8.

**Comment by csnemes** [comment]
Released Tracer.Log4Net.Fody 1.3.3 which is updated to log4net 2.0.8
