### ISSUE TITLE
Move attributes to Tracer.Fody core package?

### ISSUE THREAD

**Issue by gautelo** [csnemes/tracer#56]
I've a large solution with many projects. I've added Tracer.Fody to most of my projects and a Tracer adapter package to my host project. Though I've got to put a textual reference to the adapter in the FodyWeaver.xml, thereby adding a loose dependency on it in every project using Tracer.Fody, at least it's not a hard dependency, which is not optimal, but acceptable. I might just make those linked solution files or something anyway.

Now, I like this setup. The alternative would be to add a reference to the Tracer adapter in all of my projects. The problem with this is that it will then also add a hard dependency on my logging framework. But what if I'm not doing any other logging than Tracer in some of my projects, or what if I'm using a different logging framework, or an abstraction, such as Microsoft.Extensions.Logging (which is my scenario)? Then my project would not really need that logging framework reference. (Since it's only needed during bootstrapping.)

So far, so good. I can do that, and things work.

However, if I have a few classes I would like to not trace, I should probably just slap a couple of `[NoTrace]` attributes on them. But wait! Those are duplicated throughout all of the adapters, so attempting to do this is forcing me to add that hard dependency I'd really like to avoid.

I guess, I could try adding the exclusion rule to my FodyWeaver.xml, but I like attributes, and I think moving them to the abstraction package would make more sense. If that abstraction package should be Tracer.Fody or a new Tracer.Fody.Abstractions/Attributes/Helpers or something else is not something I have a strong opinion on.

Sadly though, I can't seem to find a way to exclude specific classes, through FodyWeaver.xml, only complete namespaces. That means I'll have to paint on broader strokes than I'd like. So, I guess I end up having to add the adapter package all over the place.

I hope you don't take this story as whining. I'm just trying to explain my reasoning and why I feel this is a serious issue.

**Comment by csnemes** [comment]
What if you define your own NoTrace attribute in one of your common libraries and use it from there. The weaver only cares about the name and namespace of the attribute and not the assembly. See step 5 of https://github.com/csnemes/tracer/wiki/Create-your-own-logging-adapter. I'm not 100% sure that it works, but you might give a try.

**Comment by gautelo** [comment]
Copying the TracerAttributes.cs to my own abstractions project works, and solves my problem. I still think you should consider moving it to Tracer.Fody, however, so I'm not gonna close the issue, and leave it for you to decide.

As an aside, I found that adding ´AttributeTargets.Struct´ allows me to controle tracing my struct methods, which I enjoy. Not sure if you omitted that target on purpose. If not, you may consider adding it.

**Comment by csnemes** [comment]
Just added the struct to attributes targets. The problem with putting the attributes into Tracer.Fody is that Tracer,Fody contains only compile time dependencies, it is not required runtime. The attributes are put on the actual classes/methods so they're required to be referenced during runtime as well, same way as Log statements.

**Comment by gautelo** [comment]
Ok. That makes sense then. I'll conclude that copying the attributes to my own project is the best-practice for my scenario and close the issue.

PS: Thanks for adding structs! ;)
