### ISSUE TITLE
MongoDB does not like Property name starting with $

### ISSUE THREAD

**Issue by DewJunkie** [csnemes/tracer#62]
$exception
$return

Do you see any issue with renaming them to something like _exception_ and _return_.  Maybe this could be configured in FodyWeavers.xml.

I guess this would be a breaking change if someone was querying by the field name.  But I was planning on submitting a pull request that had them renamed to something.  I was trying to find a reference from mongo about what a valid, but it seems that names starting with "$" are reserved of some sort in MongoDb.

**Comment by csnemes** [comment]
I think the a proper solution would be to make them configurable with a default value $exception and $return. This way it remains backward compatible. It's not a huge change so I'm sure I'll have time during the holidays to implement this.

**Comment by DewJunkie** [comment]
Awesome.  If you feel like delegating let me know.  Fody is new to me, but I've started using tracer in a few projects.

**Comment by csnemes** [comment]
Hi, sorry for the late reply. I've just released the 2.1 version of the logger adapter which supports getting the prefix from an environment variable.

**Comment by dmckinney-tg** [comment]
No worries, I've still been using the library quite a bit, but I have my own fork of the serilog implementation.  I'll try to circle back at some point and do a pull request with what I think is useful.
