### ISSUE TITLE
netcoreapp2.0 on Windows

### ISSUE THREAD

**Issue by fdesbrosses** [csnemes/tracer#63]
I got a strange problem: on a sample web app (netcoreapp2.0), Tracer is working as expected on a mac with Visual Studio for Mac. 

However, on Windows with Visual Studio (15.5.7), I got a fody error on build saying it could not load 'ModuleWeaver' because it could not find netstandard, Version=2.0.0.0.
I've tried to add the NuGet package NetStandardLibrary, but no luck. 

Anyone has any clue ?

**Comment by fdesbrosses** [comment]
I've found a temporary workaround in copying netstandard.dll from "C:\Program Files (x86)\Microsoft Visual Studio\2017\XXX\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\lib" into "C:\Users\XXX\.nuget\packages\tracer.fody\2.0.0".

**Comment by KevinYeti** [comment]
@fdesbrosses that works for me
