### ISSUE TITLE
Allow Constructors with TracerAttributes (NoTrace, TraceOn)

### ISSUE THREAD

**Issue by OliLay** [csnemes/tracer#66]
Hi,

apparently you didn't specify that the TracerAttributes can be applied to constructors also. 
As you can also weave at constructors entering and leaving, it would be useful to use the attributes at constructors.
I would suggest to add AttributeTargets.Constructor to the TraceOn and NoTrace classes. 

Kind regards,
Oliver

**Comment by csnemes** [comment]
Ok. It will be added to the next update.
