### ISSUE TITLE
Serilog should trace as Verbose rather than Debug

### ISSUE THREAD

**Issue by gautelo** [csnemes/tracer#69]
We're in the process of changing from NLog to Serilog, and so I've swapped from Tracer.NLog.Fody to Tracer.Serilog.Fody.

Unfortunately it seems that the Serilog LoggerAdapter uses `LogEventLevel.Debug` rather than `LogEventLevel.Verbose`. This makes it virtually impossible to use the Debug level for anything normal as it's being spammed by Tracer.

Contrast that with the NLog LoggerAdapter which uses `LogLevel.Trace`.

I expect this is simply due to not finding an expected `LogEventLevel.Trace` in Serilog and thus picking `LogEventLevel.Debug`. Perhaps `LogEventLevel.Verbose` did not exist when the code was written even.

Would it be possible to change this so that it makes more sense and aligns with the NLog adapter?

Many thanks! :)

**Comment by csnemes** [comment]
Give a try to the latest (2.2.1) version of the adapter.

**Comment by gautelo** [comment]
Thanks a bunch. It's working as intended!
