### ISSUE TITLE
Feature request: NoTrace specific method name across many namespaces

### ISSUE THREAD

**Issue by gautelo** [csnemes/tracer#70]
I find myself putting a lot of [NoTrace] on `GetHashCode` and `Equals` overrides. Would it be possible to add support for blocking all methods of a certain short `Name` through FodyWeavers.xml? I'm thinking something like this:

```xml
<!--Globally block a method -->
<NoTrace method="GetHashCode" />

<!--Selectively block a method -->
<NoTrace namespace="MyOrg.Parts+*" method="Equals" />
```

**Comment by csnemes** [comment]
I'm planning to create a more complex flitering mechanism than what we have today. I hope it'll be ready by the end of December/early January. It will cover your scenario too.

**Comment by gautelo** [comment]
@csnemes Sweet. Looking forward to seing what it will look like.
