### ISSUE TITLE
ITracer and ITracerManager not found after Nuget Installation?

### ISSUE THREAD

**Issue by pha3z** [csnemes/tracer#73]
The wiki says that all you need to do is add Tracer.log4net and you're good to go.

I tried this, and it adds a file called TracerManager.cs in a subfolder of External - Diagnostics - Tracer - Log4Net.

The file has errors indicating that ITracerManager and ITracer cannot be found. It asks if I'm missing an assembly or namespace reference.

I don't see anything about Tracer in the References list.  Should there be a referenced assembly?

Not really sure what to do to fix this.  Any ideas?

**Comment by csnemes** [comment]
Hi,
What type of project are you using? (netcore, netfwork, xamarin)
Are you adding Tracer.log4Net via nuget?

**Comment by pha3z** [comment]
I added Tracer.Log4net via Nuget.

The project is WPF .NET Framework 4.7.2

Is this TracerManager.cs file supposed to be there as I described?  And where is Tracer and ITracerManager supposed to come from?

**Comment by pha3z** [comment]
I downloaded the Tracer github source and searched the entire solution for ITracer and ITracerManager.  They aren't in there. 

So why is this TracerManager.cs file added by Nuget looking for those interfaces?

**Comment by pha3z** [comment]
Even more bizarre.  I googled for "TracerManager.cs"  and I found this:

[https://github.com/clariuslabs/tracerhub/blob/master/External/Diagnostics/Tracer/SystemDiagnostics/TracerManager.cs](url)

That's the file that was added to my project after I used Nuget.

That doesn't look like something the Nuget installation should be adding for Tracer.Log4Net. Is there something wrong with the Nuget package?

**Comment by csnemes** [comment]
Ok, I see now. The package is Tracer.Log4net.Fody and not just Tracer.Log4Net. I'll correct the wiki. Sorry for the inconvenience.

**Comment by pha3z** [comment]
That fixed the problem.  After installing Tracer.Log4Net.Fody, two assembly references appear:
log4net
Tracer.Log4Net

No build errors :)

Thanks for the help! I really appreciate it!!  I'm excited to try out Tracer now! It looks awesome! :)
