### ISSUE TITLE
Support for Fody v4

### ISSUE THREAD

**Issue by ndrwrbgs** [csnemes/tracer#80]
Fody Version 4 is out. I've been running with it so I think you shouldn't need changes to work with it, but the nuget package for tracer.Fody (even 3.0.0-beta) still says it requires "< 4"

**Comment by ndrwrbgs** [comment]
Oh, looks like v5 is in beta as of this morning too :-)

**Comment by csnemes** [comment]
Updated tracer 3.1 to Fody Version 4 and also removed the cap, so you can update it to Fody v5 if you wish.
