### ISSUE TITLE
Installed Tracer.Log4Net.Fody, but Weavers.XML did not Show Up

### ISSUE THREAD

**Issue by pha3z** [csnemes/tracer#89]
I installed Tracer.Log4Net.Fody into a .NET Framework 4.7.2 project.

It automatically installed the dependencies Fody, and Log4Net.

But weavers.xml did not appear in the root of my project. Is that a bug? I was under the impression that anytime Fody is added to a project, it should add weavers.xml to the project automatically.

**Comment by pha3z** [comment]
Oh my.  I found the answer already.
https://github.com/Fody/Costura/issues/270

You have to add the weavers file manually.

The Fody wiki describs it in the Getting Started page:
https://github.com/Fody/Home/blob/master/pages/usage.md

 I would like to add a note about this to the Tracer wiki if its ok with the maintainer. Would certainly have made getting up and running much easier. Cross-referencing the Fody wiki to find this out isn't easy.

**Comment by csnemes** [comment]
added to readme.txt
