### ISSUE TITLE
What is the correct way to completely disable tracer?

### ISSUE THREAD

**Issue by pha3z** [csnemes/tracer#90]
Let's say I'm finished using the Tracer on my project and I want to build the project without any IL weaving.  What would be the correct way to simply turn off the weaving so I can build the project without tracing?

I'd like to be able to just as easily turn it back on with the same configuration.

**Comment by csnemes** [comment]
You can either remove the tracer from FodyWeavers.xml or you can set DisableFody in the project file (I use a separate msbuild props file which is referenced from all my projects. This way you can switch on and off from a single file). The latter will disable all weavers. There is no switch currently in the tracer config for turning it off, but if it is needed I can add one.

**Comment by csnemes** [comment]
added a disabled switch to trace config in 3.2.
