### ISSUE TITLE
Is Tracer.4NLog.Fody the release version?

### ISSUE THREAD

**Issue by hhko** [csnemes/tracer#99]
### Environment
- Tracer.4NLog.Fody 3.3.0
- Fody 6.1.1
- NLog 4.7.0
- BenchmarkDotNet 0.12.0

### Situation
I'm testing Tracer.4NLog.Fody by BenchmarkDotNet.
It couldn't be tested. 
BenchmarkDotNet explained the reason for the failure.

```
// Validating benchmarks:
Assembly ConsoleAppTracer which defines benchmarks references non-optimized Tracer.NLog
        If you own this dependency, please, build it in RELEASE.
        If you don't, you can disable this policy by using 'config.With(ConfigOptions.DisableOptimizationsValidator)'.
```

![image](https://user-images.githubusercontent.com/12065137/77893141-846f8b00-72ae-11ea-8bb9-45a0c654bbfb.png)

**Comment by csnemes** [comment]
it was a debug version, the 3.3.1 is release version now.

**Comment by hhko** [comment]
thank you for your consideration.
